//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS481WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        public int ForumID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<long> Score { get; set; }
        public string UserID { get; set; }
    }
}
